# Generated by Django 4.2.13 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
