# Generated by Django 6.0.3 on 2026-06-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_countries'),
        ('hub', '0004_user_country_user_track'),
    ]

    operations = [
    ]
