# Generated by Django 4.2.13 on 2026-06-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_merge_0002_countries_0004_user_country_user_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cohorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
