# Generated by Django 4.2.13 on 2026-06-08 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_cohort_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
