# Generated by Django 4.2.13 on 2026-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_cohort_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
