# Generated by Django 4.2.13 on 2026-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='cohorts', to='hub.trainingtrack'),
        ),
    ]
