CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "hub_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "full_name" varchar(255) NOT NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL, "is_email_verified" bool NOT NULL, "date_joined" datetime NOT NULL, "profile_photo" varchar(100) NULL, "age" integer unsigned NULL CHECK ("age" >= 0), "nationality" varchar(100) NOT NULL, "location" varchar(255) NOT NULL, "bio" text NOT NULL, "career_goal" text NOT NULL);
CREATE TABLE IF NOT EXISTS "hub_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "hub_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "hub_cohort" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "is_active" bool NOT NULL, "applications_open" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "hub_trainingtrack" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "description" text NOT NULL);
CREATE TABLE IF NOT EXISTS "hub_otpcode" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(6) NOT NULL, "created_at" datetime NOT NULL, "is_used" bool NOT NULL, "user_id" bigint NOT NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "hub_module" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "order" integer unsigned NOT NULL CHECK ("order" >= 0), "track_id" bigint NOT NULL REFERENCES "hub_trainingtrack" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "hub_liveclass" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "scheduled_at" datetime NOT NULL, "meeting_link" varchar(200) NOT NULL, "cohort_id" bigint NOT NULL REFERENCES "hub_cohort" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "hub_moduleprogress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "completed" bool NOT NULL, "completed_at" datetime NULL, "module_id" bigint NOT NULL REFERENCES "hub_module" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "hub_user_groups_user_id_group_id_5d46d166_uniq" ON "hub_user_groups" ("user_id", "group_id");
CREATE INDEX "hub_user_groups_user_id_874d7aeb" ON "hub_user_groups" ("user_id");
CREATE INDEX "hub_user_groups_group_id_1f2d31be" ON "hub_user_groups" ("group_id");
CREATE UNIQUE INDEX "hub_user_user_permissions_user_id_permission_id_c9c1b422_uniq" ON "hub_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "hub_user_user_permissions_user_id_a4424f68" ON "hub_user_user_permissions" ("user_id");
CREATE INDEX "hub_user_user_permissions_permission_id_54eb66d8" ON "hub_user_user_permissions" ("permission_id");
CREATE INDEX "hub_otpcode_user_id_e21a3f04" ON "hub_otpcode" ("user_id");
CREATE INDEX "hub_module_track_id_9f8f32f8" ON "hub_module" ("track_id");
CREATE INDEX "hub_liveclass_cohort_id_a03d2474" ON "hub_liveclass" ("cohort_id");
CREATE UNIQUE INDEX "hub_moduleprogress_user_id_module_id_ee7cbfd0_uniq" ON "hub_moduleprogress" ("user_id", "module_id");
CREATE INDEX "hub_moduleprogress_module_id_397d32ee" ON "hub_moduleprogress" ("module_id");
CREATE INDEX "hub_moduleprogress_user_id_5e123aef" ON "hub_moduleprogress" ("user_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "dashboard_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "message" varchar(255) NOT NULL, "is_read" bool NOT NULL, "created_at" datetime NOT NULL, "user_id" bigint NOT NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "dashboard_notification_user_id_e4f6848c" ON "dashboard_notification" ("user_id");
CREATE TABLE IF NOT EXISTS "hub_application" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "status" varchar(20) NOT NULL, "submitted_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "cohort_id" bigint NULL REFERENCES "hub_cohort" ("id") DEFERRABLE INITIALLY DEFERRED, "training_track_id" bigint NULL REFERENCES "hub_trainingtrack" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL UNIQUE REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED, "motivation" text NOT NULL, "skills" text NOT NULL);
CREATE INDEX "hub_application_cohort_id_eda3fce3" ON "hub_application" ("cohort_id");
CREATE INDEX "hub_application_training_track_id_5d35ea93" ON "hub_application" ("training_track_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "token_blacklist_blacklistedtoken" ("blacklisted_at" datetime NOT NULL, "token_id" bigint NOT NULL UNIQUE REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
CREATE TABLE IF NOT EXISTS "token_blacklist_outstandingtoken" ("token" text NOT NULL, "created_at" datetime NULL, "expires_at" datetime NOT NULL, "user_id" bigint NULL REFERENCES "hub_user" ("id") DEFERRABLE INITIALLY DEFERRED, "jti" varchar(255) NOT NULL UNIQUE, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");
